language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install pylint requests
script:
  - find -name "*.py" | xargs pylint
